# syntax=docker/dockerfile:1
FROM node
ENV NODE_ENV=production

CMD [ "bash" ]
RUN apt update
RUN apt install git nano -y
RUN mkdir -p /node/web

WORKDIR /node/web

RUN git clone https://github.com/albagimeno/PROYECTO_FIN_CICLO.git

RUN mv PROYECTO_FIN_CICLO/web/* /node/web/

EXPOSE 80/tcp
EXPOSE 80/udp
EXPOSE 4000/tcp
EXPOSE 4000/udp
EXPOSE 27017/tcp
EXPOSE 27017/udp

WORKDIR /